require:
  - rubocop-rspec
  - rubocop-factory_bot

inherit_mode:
  merge:
    - Exclude

Lint/Debugger:
  Enabled: true
  Exclude: []
AllCops:
  NewCops: enable
  SuggestExtensions: false
  TargetRubyVersion: 3.3
  Exclude:
    - "Gemfile"
    - "db/schema.rb"
    - "db/migrate/*"
    - "tmp/*"
    - "bin/*"
Documentation:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Style/MixinGrouping:
  Enabled: false
Metrics/MethodLength:
  Max: 20
Naming/MemoizedInstanceVariableName:
  EnforcedStyleForLeadingUnderscores: required
Lint/MissingSuper:
  Enabled: false

RSpec:
  Enabled: false

RSpec/Focus:
  Enabled: true

RSpec/EmptyExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterExampleGroup:
  Enabled: true

RSpec/EmptyLineAfterFinalLet:
  Enabled: true

RSpec/EmptyLineAfterHook:
  Enabled: true

RSpec/EmptyLineAfterSubject:
  Enabled: true

RSpec/HookArgument:
  Enabled: true

RSpec/HooksBeforeExamples:
  Enabled: true

RSpec/ImplicitExpect:
  Enabled: true

RSpec/IteratedExpectation:
  Enabled: true

RSpec/LetBeforeExamples:
  Enabled: true

RSpec/MissingExampleGroupArgument:
  Enabled: true

RSpec/ReceiveCounts:
  Enabled: true

FactoryBot/AttributeDefinedStatically:
  Enabled: true

FactoryBot/CreateList:
  Enabled: true
