# frozen_string_literal: true

Dotenv.require_keys(
  'TWITCH_MESSAGE_SECRET',
  'TWITCH_CLIENT_ID',
  'TWITCH_CLIENT_SECRET',
  'TELEGRAM_TOKEN',
  'TELEGRAM_SECRET_TOKEN',
  'DB_ENCRYPTION_PRIMARY_KEY',
  'DB_ENCRYPTION_DETERMINISTIC_KEY',
  'DB_ENCRYPTION_KEY_DERIVATION_SALT',
  'PUBLIC_API_URL'
)
