default: &default
  twitch_message_secret: <%= ENV['TWITCH_MESSAGE_SECRET'] %>
  twitch_client_id: <%= ENV['TWITCH_CLIENT_ID'] %>
  twitch_client_secret: <%= ENV['TWITCH_CLIENT_SECRET'] %>
  telegram_token: <%= ENV['TELEGRAM_TOKEN'] %>
  telegram_secret_token: <%= ENV['TELEGRAM_SECRET_TOKEN'] %>
  public_api_url: <%= ENV['PUBLIC_API_URL'] %>
  redis_url: <%= ENV['REDIS_URL'].presence || 'redis://localhost:6379/0' %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  max_user_subscriptions: <%= ENV['MAX_USER_SUBSCRIPTIONS'] || 15 %>
  max_users: <%= ENV['MAX_USERS'] || 500 %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
