default: &default
  twitch_message_secret: <%= ENV['TWITCH_MESSAGE_SECRET'] %>
  twitch_client_id: <%= ENV['TWITCH_CLIENT_ID'] %>
  twitch_client_secret: <%= ENV['TWITCH_CLIENT_SECRET'] %>
  telegram_token: <%= ENV['TELEGRAM_TOKEN'] %>
  telegram_secret_token: <%= ENV['TELEGRAM_SECRET_TOKEN'] %>
  db_encryption_primary_key: <%= ENV['DB_ENCRYPTION_PRIMARY_KEY'] %>
  db_encryption_deterministic_key: <%= ENV['DB_ENCRYPTION_DETERMINISTIC_KEY'] %>
  db_encryption_key_derivation_salt: <%= ENV['DB_ENCRYPTION_KEY_DERIVATION_SALT'] %>
  public_api_url: <%= ENV['PUBLIC_API_URL'] %>
  redis_url: <%= ENV['REDIS_URL'].presence || 'redis://localhost:6379/0' %>
  sentry_dsn: <%= ENV['SENTRY_DSN'] %>
  max_chat_subscriptions: <%= ENV['MAX_CHAT_SUBSCRIPTIONS'].presence || 15 %>
  max_chats: <%= ENV['MAX_CHATS'].presence || 500 %>

development:
  <<: *default

production:
  <<: *default

test:
  <<: *default
